### ISSUE TITLE
Meet with Client

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#12]
**Goal of task** 
Meet with the client to clear our doubts and answer our questions

**Success or completion criteria** 
Successfully met the client and asked the questions

**Priority**
Medium

**Allocated time** 
1 hour

**Start date and end date of work done** 
6 September 2023 - 6 September 2023

**Comment by GuooJunn** [comment]
Work done
Met with client

How does the work affect success or completion criteria
Meeting with the client enabled us to ask him questions to clear our doubts and fully understand the requirements
