### ISSUE TITLE
1.2.2 Come up with ideas for Non-Functional Requirements

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#14]
**Goal of task**
Come up with non functional requirements

**Success or completion criteria**
All non functional requirements that are crucial to the product design are clearly stated

**Priority**
Medium

**Allocated time**
1 week

**Start date and end date of work done**
4 September 2023 - 8 September 2023

**Comment by GuooJunn** [comment]
**Work done**
Discussed and came up with non functional requirements to understand the functionalities of the product that we are proposing

**How does the work affect success or completion criteria**
Came up with well-defined non functional requirements
