### ISSUE TITLE
2.3 Update Architectural Design

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#20]
**Goal of task** 
To update architectural design

**Success or completion criteria** 
Updated architectural design

**Priority**
Medium

**Allocated time** 
3 Days

**Start date and end date of work done** 
29 September 2023 - 2 October 2023

**Comment by maggxng** [comment]
Work done
Checked and discussed with the team. The current architecture design is updated.

How does the work affect success or completion criteria
helped with m2 report
