### ISSUE TITLE
2.4 Update Class Diagram

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#21]
**Goal of task** 
Update class diagram based off everything that was changed

**Success or completion criteria** 
Updated class diagram

**Priority**
Medium

**Allocated time** 
4 Days

**Start date and end date of work done** 
29 September 2023 - 3 October 2023

**Comment by Jeffrey2177** [comment]
Work done
Updated the class diagram to ensure it includes all the appropriate classes

How does the work affect success or completion criteria
The work completing the class diagram allows a clearer picture when constructing other diagrams like component and sequence diagram
