### ISSUE TITLE
3.3 UI Design

### ISSUE THREAD

**Issue by maggxng** [ZuXi-Y/P2-4#29]
Goal of task
placeholder

Success or completion criteria
placeholder

Allocated time
placeholder

Work done
NIL (TO BE DONE LATER)

How does the work affect success or completion criteria
placeholder

Start date and end date of work done
placeholder

**Comment by Jeffrey2177** [comment]
Work done
The team has designed the system and all its pages to display a presentable graphical user interface using front-end languages CSS and html

How does the work affect success or completion criteria
The UI design for the website is an important aspect of the system, hence the work affect the completion criteria rather greatly
