### ISSUE TITLE
3.4.1 UI Implementation (Schedular)

### ISSUE THREAD

**Issue by maggxng** [ZuXi-Y/P2-4#31]
**Goal of task** 
placeholder

**Success or completion criteria** 
placeholder

**Priority**
placeholder

**Allocated time** 
placeholder

**Start date and end date of work done** 
placeholder

**Comment by GuooJunn** [comment]
Work done
Completed UI Implementation (Scheduler) 

How does the work affect success or completion criteria
M3 submission requirements
