### ISSUE TITLE
3.4.2 UI Implementation (Dashboard)

### ISSUE THREAD

**Issue by maggxng** [ZuXi-Y/P2-4#32]
**Goal of task** 
placeholder

**Success or completion criteria** 
placeholder

**Priority**
Medium

**Allocated time** 
placeholder

**Start date and end date of work done** 
11 September 2023 - 15 September 2023

**Comment by Shannonnsh** [comment]
**Work done**
Designed the dashboard and its layout

**How does the work affect success or completion criteria**
Gives a template view on the functionality and design of the webpage
