### ISSUE TITLE
3.6 Integration Testing

### ISSUE THREAD

**Issue by maggxng** [ZuXi-Y/P2-4#33]
**Goal of task** 
To link up all the Figma models into a storyline (correct flow)

**Success or completion criteria** 
Correct flow of Figma

**Priority**
Medium

**Allocated time** 
1 day

**Start date and end date of work done** 
24 November 2023 - 24 November 2023

**Comment by ZuXi-Y** [comment]
**Work done**
Linked up all the pages in Figma

**How does the work affect success or completion criteria**
The story was completed with the flow being correct
