### ISSUE TITLE
4.1 FrontEnd Testing

### ISSUE THREAD

**Issue by maggxng** [ZuXi-Y/P2-4#34]
**Goal of task** 
placeholder

**Success or completion criteria** 
placeholder

**Priority**
Medium

**Allocated time** 
placeholder

**Start date and end date of work done** 
placeholder

**Comment by Jeffrey2177** [comment]
Work done
The team tests the functionalities of the system on all the webpages and ensure there are no bugs or errors.

How does the work affect success or completion criteria
This helps us to produce an end product, the airline management system, which is error-free and usable for all the users
