### ISSUE TITLE
4.3 White Box Testing

### ISSUE THREAD

**Issue by maggxng** [ZuXi-Y/P2-4#36]
**Goal of task** 
To do white box testing (Report as well)

**Success or completion criteria** 
Completed whitebox testing
-    Provide pseudocode
-    Create the CFG (the graph should have at least 10 nodes and 2 decision points).
-    Calculate the cyclomatic complexity
-    Show the basis paths
-    Show the final test cases to cover all the basis paths

**Priority**
Medium

**Allocated time** 
4 day

**Start date and end date of work done** 
15 November 2023 - 18 November 2023

**Comment by ZuXi-Y** [comment]
**Work done**
Provided pseudocode for 1 scenario.
Created CFG and calculated cyclomatic complexity
Showed basis paths with final test cases to cover all basis paths.

**How does the work affect success or completion criteria**
Successfully completed whitebox requirements
