### ISSUE TITLE
4.4 Bug Fixing

### ISSUE THREAD

**Issue by maggxng** [ZuXi-Y/P2-4#37]
**Goal of task** 
placeholder

**Success or completion criteria** 
placeholder

**Priority**
placeholder

**Allocated time** 
placeholder

**Start date and end date of work done** 
placeholder

**Comment by Shannonnsh** [comment]
**Work done**
Fixes any bugs that is prevalent in the system

**How does the work affect success or completion criteria**
Ensures full functionality of the webpage
