### ISSUE TITLE
2.1 Develop a Component Diagram

### ISSUE THREAD

**Issue by maggxng** [ZuXi-Y/P2-4#40]
**Goal of task** 
To create component diagram

**Success or completion criteria** 
Created Component Diagram

**Priority**
Medium

**Allocated time** 
3 Days

**Start date and end date of work done** 
25 September 2023 - 27 September 2023

**Comment by GuooJunn** [comment]
**Work done**
placeholder

**How does the work affect success or completion criteria**
placeholder
