### ISSUE TITLE
2.2 Develop a Class Diagram

### ISSUE THREAD

**Issue by maggxng** [ZuXi-Y/P2-4#41]
**Goal of task** 
To come up with initial class diagram (that might be changed) because we have another task (update class diagram)

**Success or completion criteria** 
Class diagram accordingly to our current progress

**Priority**
Medium

**Allocated time** 
10 days

**Start date and end date of work done** 
13 October 2023 - 22 October 2023

**Comment by ZuXi-Y** [comment]
**Work done**
Created class diagram based on current progress

**How does the work affect success or completion criteria**
This meets the completion criteria. Class diagram was created.
