### ISSUE TITLE
3.3.3 Create Shift Allocation Page

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#49]
**Goal of task** 
Created shift allocation page in Figma

**Success or completion criteria** 
Page created in Figma

**Priority**
High

**Allocated time** 
1 day

**Start date and end date of work done** 
19 November 2023 - 19 November 2023

**Comment by maggxng** [comment]
Work done
Created assigned shift page 

How does the work affect success or completion criteria
Successfully completed assigned shift page which is one of the main feature in the system
