### ISSUE TITLE
3.3.4 Create Staff Profile Template

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#50]
**Goal of task** 
placeholder

**Success or completion criteria** 
placeholder

**Priority**
placeholder

**Allocated time** 
placeholder

**Start date and end date of work done** 
placeholder

**Comment by Shannonnsh** [comment]
**Work done**
Designed the staff profile page

**How does the work affect success or completion criteria**
Gives a template view on how the profile page is like and how users can interact with it
