### ISSUE TITLE
Consult Prof about M1 Report

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#51]
**Goal of task** 
Consult Prof and ask about M1 report

**Success or completion criteria** 
Prof answered all our questions

**Priority**
Medium

**Allocated time** 
1 day

**Start date and end date of work done** 
18 September 2023 - 18 September 2023

**Comment by Jeffrey2177** [comment]
Goal of task
The team consulted the professors on the M1 report and its contents

Success or completion criteria
The team has a better understanding on structuring the report.
