### ISSUE TITLE
Distribute Role for M2

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#52]
**Goal of task** 
Distribute roles to every member

**Success or completion criteria** 
Every member knows what they will be working on

**Priority**
Medium

**Allocated time** 
1 Day

**Start date and end date of work done** 
24 September 2023 - 24 September 2023

**Comment by Jeffrey2177** [comment]
Work done
Discussion has been made with the team and roles were given to each member on what they should do.

How does the work affect success or completion criteria
This work allows each team member to understand better what they are supposed to do for M2.
