### ISSUE TITLE
3.5 All other Figma Pages

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#55]
**Goal of task** 
Finish all other Figma Pages

**Success or completion criteria** 
Figma is complete.

**Priority**
High

**Allocated time** 
4 days

**Start date and end date of work done** 
21 November 2023 - 24 November 2023

**Comment by GuooJunn** [comment]
Work done
Completed figma

How does the work affect success or completion criteria
M3 submission requirements
