### ISSUE TITLE
4.6 M3 Video

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#56]
**Goal of task** 
Created M3 Video

**Success or completion criteria** 
M3 Video filmed and edited

**Priority**
Medium

**Allocated time** 
1 Day

**Start date and end date of work done** 
25 November 2023 - 25 November 2023

**Comment by maggxng** [comment]
Work done
M3 video done

How does the work affect success or completion criteria
m3 submission requirements
