### ISSUE TITLE
4.7 M3 Report

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#57]
**Goal of task** 
Finish M3 Report

**Success or completion criteria** 
Completed M3 Report 

**Priority**
High

**Allocated time** 
5 Days

**Start date and end date of work done** 
21 November 2023 - 25 November 2023

**Comment by GuooJunn** [comment]
Work done
Completed M3 Report 

How does the work affect success or completion criteria
M3 submission requirements
