### ISSUE TITLE
Distribute Roles for M1 Report

### ISSUE THREAD

**Issue by ZuXi-Y** [ZuXi-Y/P2-4#9]
**Goal of task** 
Distribute roles for M1 report so everything is doing a fair share

**Success or completion criteria** 
Each member got a part of what they need to do and is a fair share of the work needed to be done

**Priority**
Low

**Allocated time** 
1 hour

**Start date and end date of work done** 
4 September 2023 - 4 September 2023

**Comment by GuooJunn** [comment]
Work done
Discussed and assigned tasks to all group members fairly

How does the work affect success or completion criteria
Every member understands what he/she needs to do and is agreeable on the workload amount
